### PR TITLE
Add Vishwa Amarasinghe

### PR DESCRIPTION
**Pull request by VishwaAmarasinghe**
## Welcome PR details 

- SEF Hive User Name
Vishwa_Amarasinghe

- Introduce yourself thread entry url
https://sef.discourse.group/t/welcome-please-introduce-yourself/7/70?u=vishwa_amarasinghe

- How many Pull Requests have you sent to sef-repos? (Check only one)
  - [x] This is the first one 
  - [ ] 2 Including this
  - [ ] 3 - 4 Including this
  - [ ] 5 or more Including this

### CODE REVIEW

**Review by Piumal1999 — APPROVED** [review]
Thank you @VishwaAmarasinghe 

Cc: @akeel230

**Comment by VishwaAmarasinghe** [comment]
Welcome piumal brother and thx for approve it

**Comment by akeel230** [comment]
thanks @VishwaAmarasinghe

**Comment by akeel230** [comment]
@Gravewalker666 @Piumal1999 I don't have access to merge a PR in this Repo yet, please grant me access.

**Review by Gravewalker666 — APPROVED** [review]

**Comment by Gravewalker666** [comment]
cc: @akeel230

**Comment by akeel230** [comment]
@Gravewalker666 Noted. @VishwaAmarasinghe has been granted the 1st contribution badhe along with the certificate via Hive

**Pull request merged**
